import type { SheetTab } from "@/types/models";

export const SHEET_HEADERS: Record<SheetTab, string[]> = {
  Config: ["key", "value", "updatedAt"],
  Users: [
    "userEmail",
    "fullName",
    "role",
    "accessStatus",
    "accessType",
    "paypalSubscriptionId",
    "paypalCustomerEmail",
    "subscriptionStatus",
    "accessExpiresAt",
    "createdAt",
    "updatedAt",
    "notes",
  ],
  User_Settings: ["userEmail", "settingKey", "settingValue", "updatedAt"],
  Watchlist: [
    "userEmail",
    "ticker",
    "assetType",
    "sector",
    "strategy",
    "active",
    "notes",
    "createdAt",
    "updatedAt",
  ],
  Signals: [
    "signalId",
    "userEmail",
    "timestamp",
    "ticker",
    "exchange",
    "price",
    "direction",
    "setupType",
    "confidenceScore",
    "riskRating",
    "notes",
    "status",
    "source",
  ],
  Trades: [
    "tradeId",
    "userEmail",
    "date",
    "ticker",
    "direction",
    "entry",
    "stopLoss",
    "target",
    "exit",
    "pnl",
    "status",
    "lesson",
    "createdAt",
    "updatedAt",
  ],
  Risk_Log: [
    "riskId",
    "userEmail",
    "timestamp",
    "exposure",
    "dailyLoss",
    "maxRiskPerTrade",
    "openPositions",
    "warnings",
    "status",
  ],
  Alerts_Log: [
    "alertId",
    "userEmail",
    "timestamp",
    "ticker",
    "eventType",
    "message",
    "source",
    "payload",
  ],
  Journal: [
    "journalId",
    "userEmail",
    "date",
    "ticker",
    "category",
    "tags",
    "content",
    "aiSummary",
    "status",
    "createdAt",
    "updatedAt",
  ],
  Dashboard: ["userEmail", "metricKey", "metricValue", "updatedAt"],
};

export const SHEET_TABS = Object.keys(SHEET_HEADERS) as SheetTab[];
